# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-17 18:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraNamespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=100)),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_updater', models.CharField(max_length=100, verbose_name='最后操作员')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后操作时间')),
            ],
            options={
                'db_table': 'extra_namespace',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True, verbose_name='K8s用户组名')),
                ('group_pass', models.CharField(max_length=100, verbose_name='k8s用户组密码')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_updater', models.CharField(max_length=100, verbose_name='最后操作员')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后操作时间')),
            ],
            options={
                'verbose_name': 'k8s用户组',
                'verbose_name_plural': 'k8s用户组',
            },
        ),
        migrations.CreateModel(
            name='NameSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=100)),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_updater', models.CharField(max_length=100, verbose_name='最后操作员')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后操作时间')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100, unique=True, verbose_name='权限名')),
                ('p_type', models.CharField(max_length=100, verbose_name='权限类型')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_updater', models.CharField(max_length=100, verbose_name='最后操作员')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后操作时间')),
                ('expired_days', models.IntegerField(default=1, verbose_name='过期时间(天)')),
            ],
            options={
                'verbose_name': 'k8s用户组权限',
                'verbose_name_plural': 'k8s用户组权限',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='操作时间')),
                ('operation_type', models.CharField(choices=[('create', '增'), ('delete', '删'), ('update', '改'), ('select', '查')], max_length=10, verbose_name='操作类型')),
                ('operation_detail', models.TextField(verbose_name='操作日志')),
            ],
            options={
                'verbose_name': '操作记录',
                'verbose_name_plural': '操作记录',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('chinese_name', models.CharField(max_length=100, verbose_name='中文名')),
                ('is_root', models.BooleanField(default=0, verbose_name='是否超级用户')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '登录平台用户',
                'verbose_name_plural': '登录平台用户',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z_name', models.CharField(max_length=100, verbose_name='区域名')),
                ('api_server', models.GenericIPAddressField(verbose_name='APIserver地址')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_updater', models.CharField(max_length=100, verbose_name='最后操作员')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后操作时间')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域',
            },
        ),
        migrations.AddField(
            model_name='record',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='app01.User', verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='namespace',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namespace', to='app01.Zone', verbose_name='区域'),
        ),
        migrations.AddField(
            model_name='group',
            name='namespace',
            field=models.ManyToManyField(db_table='group_to_namespace', related_name='group', to='app01.NameSpace'),
        ),
        migrations.AddField(
            model_name='group',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='app01.Zone', verbose_name='区域'),
        ),
        migrations.AddField(
            model_name='extranamespace',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Group'),
        ),
        migrations.AddField(
            model_name='extranamespace',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Permission'),
        ),
        migrations.AlterUniqueTogether(
            name='extranamespace',
            unique_together=set([('group', 'namespace', 'permission')]),
        ),
    ]
